server:
  port: 8888
spring:
  application:
    name: ms-admin-config-server
#Configuracion Local
  profiles:
    active: native
  cloud:
    config:
      server: 
        native:
          searchLocations: file:///C:/Users/Erick/Documents/Erik/sts4.14/profe3/MS-02-2022/ms-admin-server-data
#Configuracion Cloud (git)
 # cloud:
 #   config:
 #     server:
 #       git:
 #         uri: https://github.com/GalaxyTraining/MS-02-2022.git
 #         search-paths:
 #         - ms-admin-server-data
 #         username: ${USER_NAME}
 #         password: ${USER_PASSWORD}
 #         clone-on-start: true
 #         force-pull: true
 #         timeout: 5
 #         default-label: 02.-SpringCloud2021