server:
  port: 8083
    
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: MS_1_GALAXY
    password: 123456789
    driver-class-name: oracle.jdbc.driver.OracleDriver

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"